# Generated by Django 4.2.18 on 2025-01-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_accountingperiod_client"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="bookkeeping_system",
            field=models.CharField(
                choices=[
                    ("QB", "QuickBooks"),
                    ("XE", "Xero"),
                    ("SP", "Sage"),
                    ("FW", "FreshWorks"),
                ],
                default="QB",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounting_periods",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["code"], name="clients_cli_code_d90b4a_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
        ),
    ]
